### ISSUE TITLE
RuntimeError: PyTorch is not linked with support for mps devices

### ISSUE THREAD

**Issue by sdwcn** [hylarucoder/svd-webui#1]
getting runtimeerror while launching main.py
-------------------------------------------------------------
Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #3: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #4: ConcatTimestepEmbedderND with 0 params. Trainable: False
Restored from models/checkpoints/svd.safetensors with 0 missing and 0 unexpected keys
Traceback (most recent call last):
  File "/mnt/data/nsd/svd-webui/main.py", line 274, in <module>
    Fire(sample)
  File "/mnt/data/nsd/svd-webui/venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/mnt/data/nsd/svd-webui/venv/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/mnt/data/nsd/svd-webui/venv/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/data/nsd/svd-webui/main.py", line 66, in sample
    model = load_model(
  File "/mnt/data/nsd/svd-webui/main.py", line 268, in load_model
    model = instantiate_from_config(config.model).to(device).eval()
  File "/mnt/data/nsd/svd-webui/venv/lib/python3.10/site-packages/lightning_fabric/utilities/device_dtype_mixin.py", line 54, in to
    return super().to(*args, **kwargs)
  File "/mnt/data/nsd/svd-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/mnt/data/nsd/svd-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/mnt/data/nsd/svd-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/mnt/data/nsd/svd-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/mnt/data/nsd/svd-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/mnt/data/nsd/svd-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: PyTorch is not linked with support for mps devices

**Comment by hylarucoder** [comment]
@sdwcn 

fixed, thx
